### ISSUE TITLE
Scripting bugs: `export: `': not a valid identifier`

### ISSUE THREAD

**Issue by rfay** [shaal/DrupalPod#129]
## Describe the bug

Doing the (apparently successful) procedure described in 
* https://github.com/shaal/DrupalPod/issues/124

I see these in the output:

`.gitpod/utils/set-base-environment.sh: line 7: export: `': not a valid identifier`

`.gitpod/drupal/drupalpod-setup.sh: line 15: export: `': not a valid identifier`

Full output at https://gist.github.com/rfay/3a29000e96f3e87459a2792603ac3376

## To Reproduce

I'm pretty sure this is happening all the time. 

What I did was use a new github/gitpod account called drud-monitoring-machine account and went through the procedure in #124

## Expected behavior

No errors or complaints

**Comment by shaal** [comment]
Fixed by PR https://github.com/shaal/DrupalPod/pull/133
