### ISSUE TITLE
Allow DrupalPod to launch from "node" link

### ISSUE THREAD

**Issue by lostcarpark** [shaal/DrupalPod#154]
## Is your feature request related to a problem? Please describe

If you share an issue with the handy short link, such as: [dgo.to/3478994](http://dgo.to/3478994), it redirects to https://www.drupal.org/node/3478994 rather than https://www.drupal.org/project/project_browser/issues/3478994, which means DrupalPod doesn't identify it as an issue that it can open.

Both URLs refer to the same ussue, but the Drupalpod extension only recognises the `/issues/` link.

## Describe the solution you'd like

Make the DrupalPod extension recognise `/node/` links.

## Describe alternatives you've considered

Currently I find the easiest workaround is to click on "issues" in the breadcrumbs, then find the issue in the list to get to the URL that DrupalPod will recognise.

## Additional context

![image](https://github.com/user-attachments/assets/4f5bdbe5-dfa6-46a9-95b5-9207fbfc2c94)

**Comment by rfay** [comment]
Please open the issue in https://www.drupal.org/project/drupalpod, the new home of Drupalpod.

**Comment by lostcarpark** [comment]
Transferred to the drupal.org issue queue. Feel free to close this one.
