### ISSUE TITLE
Add Drupal-related VSCode extensions and settings

### ISSUE THREAD

**Issue by shaal** [shaal/DrupalPod#6]
## Is your feature request related to a problem? Please describe

Working on Drupal code without supporting extensions and settings of VScode is degrading the developer experience.

## Describe the solution you'd like

Use the link below to add recommended extensions in `.gitpod.yml` file and recommended settings into `./vscode` directory.
https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code

**Comment by mradcliffe** [comment]
I think this can be closed now with #30 and follow-up #33

**Comment by shaal** [comment]
Thank you 👍
