### ISSUE TITLE
Composer requirement error using Drupal 10

### ISSUE THREAD

**Issue by robertoperuzzo** [shaal/DrupalPod#97]
## Describe the bug
During the workspace spinning up I get this error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/devel ^4.1 -> satisfiable by drupal/devel[4.1.0, ..., 4.x-dev].
    - drupal/devel[4.1.0, ..., 4.x-dev] require drupal/core ^8.8 || ^9 -> found drupal/core[8.8.0-alpha1, ..., 8.9.x-dev, 9.0.0-alpha1, ..., 9.5.x-dev] but the package is fixed to 10.0.0-alpha6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
composer [require drush/drush:^11.0 drupal/coder:^8.3 drupal/devel:^4.1 drupal/admin_toolbar:^3.1] failed, composer command failed: exit status 2. stderr=
```

## To Reproduce
Use DrupalPod Chrome extension to generate the workspace for working on a contrib module issue regarding Drupal 10.

## Expected behavior
No composer requirement errors.

## Screenshots
![Screenshot 2022-09-09 at 15 20 33](https://user-images.githubusercontent.com/6221210/189359426-6be8ec08-7382-41d3-bb9f-ba70f8b81bc0.png)

### Version and configuration information (please complete the following information)

- **Issue page** [iubenda_integration issue 3255572](https://www.drupal.org/project/iubenda_integration/issues/3255572)
- **Issue branch** [3255572-for-version-4](https://git.drupalcode.org/issue/iubenda_integration-3255572/-/tree/3255572-for-version-4)
- **Drupal core version** 10.0.x
- **Project type**
- [ ] Core
- [x] Module
- [ ] Theme

**Comment by shaal** [comment]
Thank you for reporting this, I'm looking into it

**Comment by robertoperuzzo** [comment]
@shaal probably adding the new drupal/devel release [5.0.0-beta1](https://www.drupal.org/project/devel/releases/5.0.0-beta1) at this [line](https://github.com/shaal/DrupalPod/blob/984dc864a1ba0b6a657733b1f5aeee48688a6946/.gitpod/drupal/envs-prep/create-environments.sh#L60) when `if [ "$d" == '10.0.x' ]; then`

**Comment by shaal** [comment]
Thank you @robertoperuzzo !

I added your recommendations to PR #100 and merged it to `main`. This issue is resolved.
